### ISSUE TITLE
timed out sur gros fichiers

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/bozon_ynh#15]
Salut,

impossible d'uploader des "gros" fichier. Visuellement, le fichier n’apparaît pas dans Bozon à l'issue du téléchargement.

En réalité, on se prend un timed out.

```
[error] 14687#0: *524832 upstream timed out (110: Connection timed out) while sending request to upstream, client: 192.168.1.151, server: crudelis.fr, request: "POST /bozon/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock"
```

Je pense que le plus sûr est de passer par fpm et de déclarer un `max_execution_time=` dans un php.ini ou le pool fpm directement.

Essai sur un fichier de 2.3Go seulement. Et même 1.1Go

**Comment by ewilly** [comment]
Normally it's fix. Coud you give a try ?

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost-Apps/bozon_ynh/blob/master/conf/nginx.conf#L13
Remplacer par `fastcgi_pass unix:/var/run/php5-fpm-YNH_EXAMPLE_APP.sock;` pour prendre en compte le pool fpm que tu as ajouté.

https://github.com/YunoHost-Apps/bozon_ynh/blob/master/scripts/install#L81
Ajouter `sudo sed -i "s@YNH_EXAMPLE_APP@${app}@g" ../conf/nginx.conf`
de même sur upgrade

Et je sais pas pourquoi, je vois pas d'erreur. Mais ton `final_path` fini en `/var/www//bozon` dans nginx et php.

**Comment by maniackcrudelis** [comment]
Pour ça:
https://github.com/YunoHost-Apps/bozon_ynh/blob/master/scripts/upgrade#L25

**Comment by ewilly** [comment]
Merci. J'espère ne rien avoir oublié cette fois-ci...

**Comment by maniackcrudelis** [comment]
J'ai toujours 2 problèmes, toujours un time-out dans la tronche.
Et le max upload reste bloqué à 2048. Je l'ai fixé à 10G
Je cherche mais pour le moment...

**Comment by maniackcrudelis** [comment]
Si t'as un peu de temps, je suis sur le salon jabber Yunohost
