### ISSUE TITLE
Default language only works after login

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/bozon_ynh#27]
Hi
I have default language set to 'en' while installation. But its only works after the login. The front page always show French language after logout. And have to change it manually to English every time after logout.
Is it Bozon or the package issue?

**Comment by ewilly** [comment]
Le dimanche 9 juillet 2017, 16:47:55 CEST anmol26s a écrit :
> Hi
> I have default language set to 'en' while installation. But its only works
> after the login. The front page always show French language after logout.
> And have to change it manually to English every time after logout. Is it
> Bozon or the package issue?

By default Bozon try to detect the browser language and only if it fail apply 
the language selected.
After that the language is saved in each user profile and of course can be 
change. For the login page you have to change it, login in, go to the settings 
and save.
