### ISSUE TITLE
Petits détails

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/bozon_ynh#3]
Salut,

super que tu ais entrepris de packager Bozon, j'étais sur le point de le faire!
Juste quelques petits détails:
- https://github.com/ewilly/bozon_ynh/blob/master/conf/nginx.conf#L7 et https://github.com/ewilly/bozon_ynh/blob/master/conf/nginx.conf#L16. Les limites d'upload ne correspondent pas et la limite affichée par Bozon est bien de 2Go.
- https://github.com/ewilly/bozon_ynh/blob/master/scripts/install#L57. "s@default_language='en';@default_language='$default_lang';@g" me semble préférable pour éviter des effets de bord, en particulier car tu ignores le contenu réel du fichier config.php au moment de son installation.
- https://github.com/ewilly/bozon_ynh/blob/master/scripts/install#L89. Par cette commande, tu limites l'accès à l'application au seul utilisateur choisi lors de l'installation. Tout les autres utilisateurs de Yunohost en seront privés. C'est peut-être dommage pour du partage.
- https://github.com/ewilly/bozon_ynh/blob/master/scripts/install#L79-L86. Il serait intéressant d'ajouter un accès public aux partages. Pour utiliser Bozon en partage avec des utilisateurs qui n'ont pas de compte sur le serveur.
- Et enfin, https://github.com/ewilly/bozon_ynh/blob/master/scripts/install#L42, le téléchargement de la dernière version peux être problématique. Car tu ignores au moment où elle sera installé si elle ne comporte pas de bug incompatible avec ce script.

Si il y a des points où tu as besoin d'un coup de main, ce sera avec plaisir :)
Sinon, je viens de tester l'app et ça fonctionne très bien. Dommage qu'il n'y ai pas de support ldap ni http auth (et ça semble pas dans leurs priorités!).

**Comment by ewilly** [comment]
Merci pour tes commentaires, je vais travailler sur chacun de tes points et n'hésiterai à faire appel à toi si je bloque.
- #4 
- #5 
- #6 
- #7 
- #8

**Comment by ewilly** [comment]
Chaque point a été traité. Encore merci pour tes remarques qui m'ont poussées dans de grandes reflexions :)
