### ISSUE TITLE
Commit is not up to date in the community.json

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/bozon_ynh#35]
Hellow,

I found that the commit on [community.json](https://github.com/YunoHost/apps/blob/master/community.json) is outdated, hence people installing the app via this list won't benefit from the last upgrades / improvements ...

Please create a PR to update it on the list (I do not maintain this app so it's not relevant for me to do it and it might be refused...)

ProTip™ : possibly you can now set the commit to 'HEAD', to use the latest commit of master automatically in the future. If you do this, it is strongly recommended to use a 'testing' branch for changes that are not deemed stable yet.

**Comment by ewilly** [comment]
I'm waiting for good result in ci-stretch before committing community.json otherwise there is no interest to do it now

**Comment by alexAubin** [comment]
Alrighty, thank you ! :+1:

**Comment by alexAubin** [comment]
Oh actually : if you don't wanna wait too much for tests to arrive, you can learn how to use the "dev CI" where you can push yourself jobs on it : https://ci-apps-dev.yunohost.org/jenkins/

You can learn how to use it here : https://forum.yunohost.org/t/proposition-for-a-new-non-official-ci/3595/6 (basically, first thing is to ask for an access to us on the app chatroom, by providing your SSH key)

**Comment by ewilly** [comment]
Done [https://github.com/YunoHost/apps/pull/521](url)
