### ISSUE TITLE
http://bozon.pw is down

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/bozon_ynh#36]
Hello,

The website of Bozo (http://bozon.pw) is down and the latest commit (https://github.com/broncowdd/BoZoN) was on 25 Aug 2017.
Will Bozon for Yunohost keep being maintained? and more and more integrated (yunohost users instead of creating application users...)?

Best regards,
Thatoo

**Comment by ewilly** [comment]
Hello,
Yes @broncowdd was working on a v3 but I don't' know if it still on going or stopped. Last news about it is on december 17.
In any case as long as Bozon is well working with yunohost and debian without security issue, i will maintain it. Connecting users with their yunohost acount is an issue open here [https://github.com/broncowdd/BoZoN/issues/197](url).

**Comment by anmol26s** [comment]
@ewilly 
The link is not working.

**Comment by broncowdd** [comment]
I'm still working on V3 but I'm out of time :-/ That's why I don't commit on the current version.
The bozon.pw web site is down because I did'nt renew the domain. 
Don't worry, I'm working ;-)
