### ISSUE TITLE
Problème à l'installation

### ISSUE THREAD

**Issue by inrepublica** [YunoHost-Apps/bozon_ynh#41]
Bonjour,

Sur mon instance Yunohost je tente d'installer Bozon. L'installation se déroule sans accroc mais impossible de me logger dans bozon. J'essaye avec comme nom d'utilisateur l'administrateur de mon instance Yunohost et comme mot de passe celui choisi lors de l'installation mais rien n'y fait il recharge simplement la page de connexion sans aucune autre indication. Par contre si j'essaye avec un autre nom d'utilisateur la j'ai bien une erreur "identifiant inconnu".

**Comment by emiliien** [comment]
Ok.
J'ai eu le même problème.
Le script rajout la première lettre de ton nom de famille.
Tu peux aller voir sur le fichier de conf suivant : 

/var/www/bozon/private/auto_restrict_users.php c'est indiqué.
vérifie le nom du compte et si tu es bien en superAdmin 
++

**Comment by inrepublica** [comment]
En essayant de nouveau plus de problèmes c'est bien mon nom d'utilisateur qui fonctionne.
