### ISSUE TITLE
Petits détails #3.3 -> allowed users

### ISSUE THREAD

**Issue by ewilly** [YunoHost-Apps/bozon_ynh#6]
https://github.com/ewilly/bozon_ynh/blob/master/scripts/install#L89. Par cette commande, tu limites l'accès à l'application au seul utilisateur choisi lors de l'installation. Tout les autres utilisateurs de Yunohost en seront privés. C'est peut-être dommage pour du partage.

**Comment by maniackcrudelis** [comment]
Je reviens en mettre une petite couche, mais petite promis ;)
C'est lié au fonctionnement de Bozon, mais si tu ne fixes pas l'admin, le premier user qui se connectera deviendra de fait l'admin.
C'est assez étrange comme fonctionnement d'ailleurs!

J'ai pas rejeté un coup d'oeil dernièrement, mais il faudrait pouvoir créer l'admin directement à partir du script d'install.

**Comment by ewilly** [comment]
Au tout départ c'est ce que j'avais essayé mais suis arrivé au bout de mes compétences et ai donc abandonné. De l'aide serait bienvenu. 
Tentative initiale : [https://github.com/ewilly/bozon_ynh/blob/75df9edb8c923313fd6a1f9f3ced318014e32337/scripts/install#L79](url)

**Comment by maniackcrudelis** [comment]
Je vois que tu passais par un curl, tu peux aussi le tenter après l'install en forçant la première connexion avec un curl.
Ou regarder comment il créer l'user et où il le stocke pour le faire manuellement. Si c'est possible.

Je jetterais un coup d'oeil. J'ai moins de temps cette semaine, mais je vais me concentrer là dessus.

**Comment by maniackcrudelis** [comment]
L'existence d'un utilisateur est lié à sa présence dans le fichier private/auto_restrict_users.php. Qui est créé pour l'admin lors de l'enregistrement du premier user.

```
    <?php

    # user : nomuser
    $auto_restrict["users"]["nomuser"]["login"]='nomuser';
    $auto_restrict["users"]["nomuser"]["encryption_key"]='cd09dfa745ff9bda62bfa5e8a195a';
    $auto_restrict["users"]["nomuser"]["salt"] = '}Ri1n>I7.{IfOkK={\'e(Z$CP}P_N6LDAk+:Z);{vJ;6zK?z69fiT%[{@d*DVvxyQ;nK8Xd;mzm?1gK,+nt)3Nkut+QLR{JXpY0B^OZH|hm7i<_8lAIq&+|D5e#5+E;$aE)#b[ixZX,@&Jp3UEwMAJJsV:r:`,OY-G|F-K;HiHf57UMeRR=:s/ww*OpyCA4oFoP?~AcVHkN>LAFD$&yP3/ZEt-,W+zOXq<xZU)t9Re-i[=\'pF}{2\\C_/>VtGxH)TKfCO]PMHy%<v%7$#IX~]&3HchNjKsE&A)tXpk{sYj)%#5FDKl46%+2Ci.E1$i1f#]7y{zuRCMw@f]nt|yll4GHo45^$5QsQ1Xx5/?ek&9qSR><Bj)7v11qy{Dtw{h?16)t_7c|8:T[ARn6XYW@}O5i+<j8kInae4mgmJIn@tC:GF4Y)r&V|-3@..9@.\'|RArf^mT\\\\]F6EHY7IgWIT{_WtqiJxxh(70,[4hfWRu2xNwUSWoz\'XNr([nF*fqC';
    $auto_restrict["users"]["nomuser"]["pass"] = 'ce435c85a8027a3897ea8e7613839cad0cb13af25c8f0ec62862ce17ba45a4221f1db17dce31ff8d9b1cca83a23cf28f5a9a9267f38e1efac134709dcae5f';
    $auto_restrict["users"]["nomuser"]["status"]='superadmin';
    $auto_restrict["users"]["nomuser"]["lang"]='fr';

    ?>
```

L'utilisateur est créé ici
https://github.com/broncowdd/BoZoN/blob/master/core/auto_restrict.php#L127-L146

L'encryption_key, le salt et le pass nécessite un peu de travail.
encryption_key: [md5](http://php.net/manual/fr/function.md5.php) et [uniqid](http://php.net/manual/fr/function.uniqid.php)
password: [hash](http://php.net/manual/fr/function.hash.php)
Par contre, je ne trouve pas sa fonction generate_salt pour le salt.

**Comment by maniackcrudelis** [comment]
Trouvé!
https://github.com/broncowdd/BoZoN/blob/master/core/core.php#L704-L710

En somme, un petit php devrait permettre de créer l'user admin sans problème.

Mais il faut installer le paquet php5-cli

**Comment by ewilly** [comment]
J'ai egalement avancé de mon côté et trouvé une solution fonctionnelle avec curl. T'en penses quoi ?

**Comment by maniackcrudelis** [comment]
Je me suis pas encore penché sur curl.
La méthode curl est sans doute la plus simple et la plus fiable (si Bronco fait une modif sur la création d'user, ça passera toujours en curl).
Mais j'ai souvenir d'avoir lu (je trouve plus ma source) que pour les app Yunohost, l'équipe préférais qu'on évite d'utiliser curl.
Cela étant, j'ai packagé des app en utilisant curl!

En revanche, en explorant cette possibilité pour la création de l'admin, il m'est venu l'idée que ça pourrait aussi servir à ajouter les utilisateurs Yunohost via un hook. Mais pour ça, je bute toujours sur le même problème, je ne sais pas comment récupérer le mot de passe dans la base ldap...

A première vue, ta modif dans le code pour curl est nickel. Tu l'as testé pour être sûr qu'elle passe?

**Comment by ewilly** [comment]
Tous mes essais fonctionnent avec les 2 derniers commits.
