### ISSUE TITLE
Petits détails #3.4 -> skipped_uris

### ISSUE THREAD

**Issue by ewilly** [YunoHost-Apps/bozon_ynh#7]
https://github.com/ewilly/bozon_ynh/blob/master/scripts/install#L79-L86. Il serait intéressant d'ajouter un accès public aux partages. Pour utiliser Bozon en partage avec des utilisateurs qui n'ont pas de compte sur le serveur.

**Comment by ewilly** [comment]
si le yunohoster opte pour une installation publiquement visible il n'y a pas de souci sinon seuls les utilisateurs de yunohost pourrons partager -> ca me parait plus bien comme choix

**Comment by maniackcrudelis** [comment]
L'installation publique implique aussi de laisser l'app vulnérable si elle contient une faille. C'est l'un des gros intérêt du sso.
Un autre problème, lié à la création de l'user admin, est que si un user installe l'app en public sans y accéder directement. Il cours le risque de se voir spoiler l'accès admin. (Mais c'est une autre issue!)

Si une app est installée pour les users de Yunohost, il est bien souvent préférable qu'elle reste protégée par le sso.
Mais pour une app destinée à partager des fichiers, un utilisateur aura tôt ou tard besoin de partager avec une personne qui n'est pas sur le serveur.

D'autant plus que le partage entre utilisateur n'est pas encore supporté par Bozon.

Si mes souvenirs sont bon, les partages ajoutent ?f= après le path. Ce schéma facilite le passage des partages en public en gardant le coeur de l'app privée.

**Comment by ewilly** [comment]
Si je comprends bien : il faudrait abandonner le mode public pour passer par le sso sauf si l'url contient `?f=` il faut qqch de ce genre `sudo yunohost app setting bozon skipped_regex -v "^\/bozon\/?index.php?f=?"` ?

**Comment by maniackcrudelis** [comment]
Brièvement (j'essayerais de regarder demain, mes vacances étant terminées), garder le mode public me semble une bonne idée. J'imagine tout à fait des applications où Bozon serait utilisé avec un groupe de personnes qui n'a pas forcément un compte sur le serveur.

Mais par contre, en mode privé, je pense qu'il y aura toujours une situation ou un utilisateur voudra envoyer un fichier à une personne qui n'a pas de compte.
Pour moi c'est plutôt ce mode qui doit être modifié pour autorisé le partage public.
Je ne me souvient plus (j'ai pas d'instance sous la main, faut que j'en remette une) si il est possible  de sécurisé un partage par mot de passe pour des cas où la confidentialité serait primordiale.

De manière générale, tu devrais pouvoir t'inspirer de ce qui est fait sur Lutim.
https://github.com/YunoHost-Apps/lutim_ynh/blob/master/scripts/install#L133-L138
ou Radicale
https://github.com/YunoHost-Apps/radicale_ynh/blob/master/scripts/install#L200-L207
Ce sont des cas plus complexe, mais ça donne une idée.

Je pense que le mieux serait simplement de passer par un 'unprotected_regex' sur le ?f=

**Comment by ewilly** [comment]
voilà qui fonctionne (il manque tout de me de la doc sur les regex por SSOWAT)

**Comment by maniackcrudelis** [comment]
Ça fonctionne pour toi!?

J'ai passé quelques heures dessus. Pour moi c'est pas si simple.
Utiliser unprotected_regex fonctionne certes pour la page de download. Mais pas pour les images et le css associé. Du coup la page est nue!

Donc j'ai pris le problème à l'inverse.
Je met un skipped ou un unprotected sur la racine (mais le unprotected sert à transmettre les identifiants par http auth. Bozon ne gère pas le HTTP AUTH il me semble. Donc skipped va bien)

```
"skipped_urls": [
        "domain.tld/bozon",
```

Et ensuite je protège ce qui doit l'être. Soit l'index de l'application (bozon/index.php) et les pages nécessitant une authentification (index.php?p=)

```
"protected_regex": [
        "domain.tld\/bozon\/index.php($|\?.*p=.*$)"
```

Mais ça ne passe pas. Je me tape un 500 avec cette regex. Pour une raison simple... C'est pas vraiment des regex, mais du pattern lua. C'est pas tout à fait les mêmes règles...

http://wxlua.free.fr/Tutoriel_Lua/Tuto/Strings/strings6.php
Je vais essayer de faire justement un petit récap de tout ça sur le forum pour en discuter et échanger et faire une doc pour le packaging.
C'est pas la première fois que je m'arrache les cheveux là dessus sans comprendre!

**Comment by maniackcrudelis** [comment]
C'est dingue...
Le pattern est matché en unprotected_regex, mais il ne l'ai pas en protected_regex. Alors que c'est le même pattern!

Ce qui, je pense, devrait passer est

```
        "domain.tld/bozon/index.php$",
        "domain.tld/bozon/index.php%?.*p=.*$"
```

Et d'ailleurs ça marche! Sauf sur protected_regex!

**Comment by ewilly** [comment]
hum chez moi ca fonctione
pour essai

**Comment by maniackcrudelis** [comment]
Ça me rappelle un vieux souvenir ça.
Mais c'était parce-que j'avais un tiret dans mon nom de domaine, et c'était interprété. Depuis je le remplace par un point!

Pourtant, ça marche très bien chez toi en effet!

**Comment by maniackcrudelis** [comment]
Tu utilises quelle syntaxe par contre?
unprotected_regex sur /index.php%?f=.*$ ?

**Comment by ewilly** [comment]
oui : `unprotected_regex -v "$domain$path/index.php%?f=.*$"`

**Comment by maniackcrudelis** [comment]
Oui d'accord, ça me rassure. Moi aussi ça marche ça.
Mais partage un dossier et accède-y en navigation privée.
Le fichier en lui même passe, mais pas le reste

**Comment by ewilly** [comment]
Partage de dossier, ca marche mais l'affichage est à son strict minimum. Il y a effectivement une différence en mode naviguation privé mais reste fonctionnel. J'en ai profité pour ajouter `"$domain$path/index.php%?zipfolder=.*$"` pour le téléchargement de dossier en zip.

**Comment by maniackcrudelis** [comment]
En fait, je discute avec les gars de l'équipe.
Et effectivement,on a faire à un bug sur le parsing de la regex en protected.
Je termine des tests pour affirmer le bug.

Je sais pas ce que t'en penses. Mais je trouve ça plus propre si l'affichage est complet.
Du coup je préfère protéger la partie privée, pour que la page de partage soit propre.

**Comment by maniackcrudelis** [comment]
La correction du bug est en PR.
https://github.com/Kloadut/SSOwat/pull/55

De toute manière, je pense que la mise à jour va prendre un peu de temps. Donc en attendant, nous devrions garder unprotected_regex qui reste tout de même fonctionnel.
Et je vais faire un PR à merger quand le bug sera corrigé.

Si ça te convient.

PS: Je viens de faire un essai avec un fichier texte, y'a un peu d'interface derrière quand même.

**Comment by ewilly** [comment]
en ajoutant à unprotect_regex `"$domain$path/core/js/.*$","$domain$path/templates/.*$"` il n'y a plus de problème d'affcihage par contre niveau sécurité j'ai un avec l'ouverture d'accès à `core/js/`. t'en penses quoi ?

**Comment by ewilly** [comment]
hum en fait `"$domain$path/core/js/.*$"` n'est à priori pas utile. Ajouter `"$domain$path/templates/.*$"` semble régler le problème.

**Comment by maniackcrudelis** [comment]
Sur un partage d'image, de fichier texte et de dossier (tout réuni), il demande l'accès à ces fichiers:
- /index.php...
- /templates/default/css/markdown.css
- /core/js/qr.js
- /templates/default/css/style.php
- /core/js/VanillaJS.js
- /core/js/lightbox.js
- /templates/default/img/lightbox/prev.png
- /templates/default/img/lightbox/next.png
- /templates/default/img/lightbox/close_white.png
- /templates/default/img/header/logo.png

Tout filtrer risque d'être délicat. D'autant plus que selon le type de fichier partagé, il ne requiert pas les mêmes dépendances.

A mon avis, pour le moment, le plus simple est de déprotéger index.php?f, zipfolder, template et core/js. Et ensuite de passer sur protected qui se limitera à index.php$ et p=.
Ça fera toujours moins de ligne dans le sso.
Toutefois, bientôt (quand?), les regex devrait passer à PCRE et donc supporter le |. Ce qui permettra de grouper les regex dans le sso.

Rendre public /core/js/... Oui c'est sûr, c'est pas le mieux. Mais c'est nécessaire pour le partage public.
A la limite, met un 3e choix dans le manifest. Pour un privé sans partage.

**Comment by ewilly** [comment]
ok j'ai donc mis ceci `sudo yunohost app setting $app unprotected_regex -v "$domain$path/index.php%?f=.*$","$domain$path/index.php%?zipfolder=.*$","$domain$path/core/js/.*$","$domain$path/templates/.*$","$domain$path/private/temp/.*%.zip$"` (et fait une modif à la conf nginx :   #11).
Est-ce ok ainsi ?

**Comment by maniackcrudelis** [comment]
```
sudo yunohost app setting $app unprotected_uris -v "/"
```

est inutile avec le else (https://github.com/ewilly/bozon_ynh/blob/master/scripts/install#L116). Car tu l'as déjà fait en amont pour curl.

Pour unprotected_regex, ça me semble ok.
Juste pour le domaine, tu ne peux pas l'inclure directement, car si il contient un tiret (-), il va fausser la regex.
Et la path ne doit pas contenir de / final, sinon de la même manière, la regex ne passera pas.
https://github.com/YunoHost-Apps/lutim_ynh/blob/master/scripts/install#L36-L40
Remplacer par %- serait peut-être mieux d'ailleurs.

**Comment by ewilly** [comment]
ok
- j'ai supprimé le else inutile
- j'ai passé domain et path à la moulinette pour y insérer % devant chaque caractère spécial
- pour le / à la fin de path c'était bon [https://github.com/ewilly/bozon_ynh/blob/master/scripts/install#L22-L23](url)
