### ISSUE TITLE
Petits détails #3.5 -> Last master version of Bozon or not

### ISSUE THREAD

**Issue by ewilly** [YunoHost-Apps/bozon_ynh#8]
Et enfin, https://github.com/ewilly/bozon_ynh/blob/master/scripts/install#L42, le téléchargement de la dernière version peux être problématique. Car tu ignores au moment où elle sera installé si elle ne comporte pas de bug incompatible avec ce script.

**Comment by ewilly** [comment]
Chaque solution a ses avantages
Bronco est particuliérement actif, je préfère donc laisser le choix au yunoster d'installer une version de Bozon que je considère stable (par défaut) ou la version master. La méthode choisie pour updater la version stable ne m'obligera pas à mettre à jour la version de bozon_ynh dans community

**Comment by maniackcrudelis** [comment]
Je suis d'accord avec toi, pouvoir utiliser la dernière version est plutôt une bonne idée. Surtout que Bronco est très actif en effet.
Par contre, tu t'exposes au risque que ton script soit incompatible avec la version stable. Sauf à bétonner ton script d'install pour qu'il détecte les éventuelles erreurs qu'il pourrait rencontrer.

**Comment by ewilly** [comment]
Pour le moment je vérifie réguliérement et le risque est faible mais suis d'accord avec toi sur le principe. Je laisse l'issue ouverte et changerai cela plus tard.
